name = "projectchula888-api"
compatibility_date = "2024-04-20"
node_compat = true

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "project888"
database_id = "13666e3a-8af7-40e6-8654-87c26fb8f1bb"

# [ai]
# binding = "AI"